# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DYZB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'KakaJSON', '1.1.2'
    pod 'Alamofire', '4.9.1'
    pod 'Kingfisher', '4.10.1'
  # Pods for DYZB

  target 'DYZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYZBUITests' do
    # Pods for testing
  end

end
